name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android_ios:
    runs-on: macos-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'   # ✅ pinned stable version
          architecture: arm64         # ✅ required for Apple Silicon runners

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

        # 🔹 Read existing iOS build number and increment
      - name: Get iOS build number
        run: |
            INFO_PLIST=ios/Runner/Info.plist
            if [ -f "$INFO_PLIST" ]; then
                ${FLUTTER_BUILD_NUMBER}=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFO_PLIST")
                echo "Current iOS build number: $CURRENT_BUILD_NUMBER"
                NEW_BUILD_NUMBER=$((${FLUTTER_BUILD_NUMBER} + 1))
            echo "BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $GITHUB_ENV
            else
                echo "BUILD_NUMBER=1" >> $GITHUB_ENV
            fi

             # 🔹 Build APKs/IPAs for all flavours with auto-incremented patch
      - name: Build APKs/IPAs for all flavours
        run: |
          FLAVOURS=("flavour1" "flavour2" "flavour3")  # Add your flavours here
          BASE_VERSION="1.0"
          TOTAL_FLAVOURS=${#FLAVOURS[@]}
          INDEX=0

          for FLAVOUR in "${FLAVOURS[@]}"; do
            INDEX=$((INDEX+1))
            # Patch = BUILD_NUMBER + flavour index - ensures unique version per flavour
            PATCH=$(( BUILD_NUMBER + INDEX - 1 ))
            APP_VERSION="$BASE_VERSION.$PATCH"
            echo "Building flavour: $FLAVOUR with version: $APP_VERSION and build number: $PATCH"

            # Android APK
            flutter build apk --release \
              --flavor $FLAVOUR \
              --build-name=$APP_VERSION \
              --build-number=$PATCH

            # iOS IPA
            flutter build ipa --release --no-codesign \
              --flavor $FLAVOUR \
              --build-name=$APP_VERSION \
              --build-number=$PATCH

            # Save artifacts
            mkdir -p artifacts/$FLAVOUR
            cp build/app/outputs/flutter-apk/app-release.apk artifacts/$FLAVOUR/app-$FLAVOUR-$APP_VERSION.apk || true
            cp build/ios/ipa/*.ipa artifacts/$FLAVOUR/app-$FLAVOUR-$APP_VERSION.ipa || true
          done


      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release \
            --build-name=$APP_VERSION \
            --build-number=$PATCH

      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign \
            -t lib/main.dart \
            --build-name=$APP_VERSION \
            --build-number=$PATCH
            --export-method ad-hoc

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
